### PR TITLE
Prefer dot notation in CoffeeScript

### PR DESCRIPTION
**Pull request by srt32**

### CODE REVIEW

**Comment by srt32** [comment]
@adamhadani @allisonfong @Phylodome thoughts?

**Comment by adamhadani** [comment]
I realized I commented on this in https://github.com/globality-corp/guides/issues/8, my take is:
1. For CoffeeScript class definitions (resource = new Resource(..)) use dot notation
2. For dictionaries ( a = {} )  use brackets

This makes distinction in code easier as well to my mind between real 'objects' (with instance methods ) and plain old dicts

**Comment by srt32** [comment]
@adamhadani could you write out a few examples? Is another way to say it, if you're reading or writing an attribute on an instance, use dot notation. If you're reading or writing an attribute from a POJO use brackets with strings?

**Comment by Phylodome** [comment]
IMHO I don't think something like this needs a standard as there are many contextually relevant aspects that influence whether I'd prefer one over the other.

For example (and setting aside the [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter)), when referencing a piece of nested data I generally prefer:

```javascript
x.y.z
```

to:
```javascript
x['y']['z']
```

I find the reduced cognitive overhead worth any ambiguity about what you're operating on, as that ambiguity should be managed in the context of the surrounding code.

Furthermore, I generally reserve bracket notation for cases in which I must absolutely use it.  For example, when interpolating variables:
```javascript
foo = x[bar]
```

This departure from dot notation signifies that the developer should pay attention because something slightly more complex is going on here.  it attracts the eye when scanning the code, as it should, and I find the flexibility to use both forms useful.

Finally, the distinction between objects behaving as classical instances and plain objects containing data seems somewhat specious when it comes to JS, as all objects are fundamentally the same from the perspective of the language.  This differs in ES2015 (ES6), as classes become first class citizens, and I understand that CoffeeScript also has classes, but I don't feel the distinction should be drawn so starkly (perhaps this is my general bias against OO design and preference for the functional style).

Ultimately, though, this feels like micro-managing the code.  One of the core ideas at Netflix, and one that I think is worth considering here, was 'Freedom and Responsibility'.  Constraints are valuable, but we need to have the confidence in ourselves that we're hiring developers that will write clear, concise, and understandable code without being told how to structure every semantic form.  If we can do that, I don't think a convention like this is necessary.

**Comment by adamhadani** [comment]
Tend to agree, we're walking fine line of
Nitpicking here - and this specific issue is particularly painful in that
regards.
Let's stick with the wording of generally preferring dot notation over
brackets unless makes sense in context as seems to be overall inclination
here, and accept the fact brackets will come up when developers feel need
for them? Can still challenge usage in code reviews of feeling strongly
about it for whatever reason but I agree to matts point of not bogging down
developers with too much micromanagement of code upfront..

**Comment by srt32** [comment]
All makes sense. So no guide or use "prefer"?

**Comment by adamhadani** [comment]
I think "prefer" is fine as general guideline to put there

**Comment by srt32** [comment]
I'll leave this PR open until EOD for any last opinions.

**Comment by Phylodome** [comment]
'Prefer' works for me. :+1:

**Comment by allisonfong** [comment]
'prefer' sounds good to me.

**Pull request merged**
